# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('telephone_mobile', models.CharField(max_length=10)),
                ('telephone_home', models.CharField(max_length=10)),
                ('telephone_office', models.CharField(max_length=10)),
                ('fax_number', models.CharField(max_length=10)),
                ('appointment_datetime', models.DateTimeField()),
                ('institution', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
